# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='template_json',
        ),
        migrations.AlterField(
            model_name='company',
            name='begin',
            field=models.DateField(default=datetime.date(2017, 1, 13)),
        ),
    ]
